create users list component
alkemyTech/OT257-Client pull request #20
Opened 2022-07-20 20:13 UTC by eugedallasta

![image](https://user-images.githubusercontent.com/71835912/180073025-40f17eff-5c92-4324-b226-0f3c99203478.png)

2022-07-21 21:03 UTC, anagon88 requested changes

2022-07-21 21:03 UTC, anagon88 commented on src/app/features/pages/backoffice/users-list/users-list.component.html
> +      <h5 style="margin-top: 30px" *ngIf="users.length == 0">
tratar de no usar estilos en el html, moverlo al scss

2022-07-21 21:03 UTC, anagon88 commented on src/app/features/pages/backoffice/users-list/users-list.component.html
> +      <table *ngIf="users.length > 0" class="table table-striped mt-5">
*ngIf="users.length" es mas corto

2022-07-21 21:03 UTC, anagon88 commented on src/app/features/pages/backoffice/users-list/users-list.component.ts
> +    { name: 'Juan Perez', email: 'mail@gmail.com' },
no meter datos mockeados en los controller

2022-07-21 21:58 UTC, eugedallasta commented on src/app/features/pages/backoffice/users-list/users-list.component.html
> +      <h5 style="margin-top: 30px" *ngIf="users.length == 0">
arreglado

2022-07-21 21:58 UTC, eugedallasta commented on src/app/features/pages/backoffice/users-list/users-list.component.html
> +      <table *ngIf="users.length > 0" class="table table-striped mt-5">
arreglado

2022-07-21 21:59 UTC, eugedallasta commented on src/app/features/pages/backoffice/users-list/users-list.component.ts
> +    { name: 'Juan Perez', email: 'mail@gmail.com' },
el ticket decí mochearlos, pero ya los traje desde el servicio

2022-07-22 00:11 UTC, anagon88 approved these changes

2022-07-22 11:31 UTC, merged