Organization Member listing component for "About Us" page
alkemyTech/OT257-Client pull request #36
Opened 2022-07-26 15:51 UTC by ValentinaRippe

![liststaff](https://user-images.githubusercontent.com/94970159/181052427-61317091-9527-4b20-8859-e56d0b611aff.png)

2022-07-26 18:12 UTC, anagon88 requested changes

2022-07-26 18:12 UTC, anagon88 commented on src/app/features/pages/about/staff-list/staff-list.component.ts
> +    <div class="row row-cols-lg-4 row-cols-md-3 g-3 d-flex justify-content-center">
separarlo en un html

2022-07-26 19:02 UTC, ValentinaRippe commented on src/app/features/pages/about/staff-list/staff-list.component.ts
> +    <div class="row row-cols-lg-4 row-cols-md-3 g-3 d-flex justify-content-center">
Ya agrege el html

2022-07-28 16:12 UTC, anagon88 approved these changes

2022-07-28 16:13 UTC, merged