Features/ot257 27
alkemyTech/OT257-Client pull request #4
Opened 2022-07-15 15:01 UTC by wilago

Se crea los formularios de creacion de novedades y edicion sobre la misma carpeta news, se de deben mover estos componentes a la carpeta  backoffice, pero se debe hablar con el equipo para coordinar la estructuras de todas las carpetas.
Una vez organizado se puede pensar en optimizar realizando un componente para el formulario.

2022-07-15 16:17 UTC, anagon88 requested changes

2022-07-15 16:17 UTC, anagon88 commented on src/app/features/pages/news/new-form/new-form.component.ts
> +          Object.values( control.controls ).forEach( control => control.markAsTouched() );
no hace falta Object.values( control.controls ), dirrectamente control.controls.foreach ...

2022-07-15 16:17 UTC, anagon88 commented on src/app/features/pages/news/news-form/news-form.component.ts
> +    //console.log("Forma",this. form);
borrar

2022-07-15 16:17 UTC, anagon88 commented on src/app/features/pages/news/news-form/news-form.component.ts
> +      //console.log('data:image/png;base64,' + btoa(e.target.result));
borrar

2022-07-15 16:17 UTC, anagon88 commented on src/app/features/pages/news/news-form/news-form.component.ts
> +     console.log("Forma2",this. form.value);
borrar

2022-07-15 16:17 UTC, anagon88 commented on tsconfig.json
> +    "strict": false,
no cambiar esto

2022-07-15 19:32 UTC, wilago commented on src/app/features/pages/news/new-form/new-form.component.html
> +                          <!-- <label for="name">Nombre de Categoria</label> -->
Se borra codigo comentado

2022-07-15 19:33 UTC, wilago commented on src/app/features/pages/news/new-form/new-form.component.html
> +                            <!-- <textarea formControlName="description" class="form-control border-0 border-bottom shadow-none" placeholder="Descripción de categoría..." id="description" style="heig
Se borra codigo comentado

2022-07-15 19:34 UTC, wilago commented on src/app/features/pages/news/new-form/new-form.component.ts
> +            //console.log('data:image/png;base64,' + btoa(e.target.result));
Se borran lineas comentadas

2022-07-15 19:34 UTC, wilago commented on src/app/features/pages/news/new-form/new-form.component.ts
> +      console.log(this.form.value)
Se borra

2022-07-15 19:46 UTC, wilago commented on src/app/features/pages/news/news-form/news-form.component.ts
> +    //console.log("Forma",this. form);
Borrado

2022-07-15 19:47 UTC, wilago commented on src/app/features/pages/news/news-form/news-form.component.ts
> +     console.log("Forma2",this. form.value);
Borrado

2022-07-15 19:49 UTC, wilago commented on tsconfig.json
> +    "strict": false,
Se deja como estaba

2022-07-15 21:54 UTC, wilago commented on tsconfig.json
> +    "strict": false,
Se realizo el cambio

2022-07-16 19:35 UTC, anagon88 requested changes

2022-07-16 19:35 UTC, anagon88 commented on src/app/features/pages/news/news-form/news-form.component.ts
> +
formatear documento con prettier

2022-07-16 19:35 UTC, anagon88 commented on src/app/models/new.model.ts
> +    //created_at: string;
borrar comentado

2022-07-16 19:35 UTC, anagon88 commented on src/app/services/categories.service.ts
> +
formatear documento

2022-07-18 14:05 UTC, anagon88 approved these changes

2022-07-18 14:16 UTC, merged