Features/ot257 81
alkemyTech/OT257-Client pull request #40
Opened 2022-07-27 01:12 UTC by gastoncorrea

![service api](https://user-images.githubusercontent.com/74715944/181138989-322a9f01-1fb0-4ec1-a95c-840c85f0161a.png)

2022-07-28 16:15 UTC, anagon88 requested changes

2022-07-28 16:15 UTC, anagon88 commented on src/app/features/pages/back-office-home/back-office-home.component.ts
> +    // this.getSlides();
borrar codigo comentado

2022-07-28 16:15 UTC, anagon88 commented on src/app/features/pages/backoffice/users-list/users-list.component.ts
> +    // this.getUsers()
esta bien todo este codigo comentado?

2022-07-28 19:33 UTC, gastoncorrea commented on src/app/features/pages/backoffice/users-list/users-list.component.ts
> +    // this.getUsers()
lo comente porque faltaba un cambio de otro componente
 en el codigo para que funcione mi rama y les avise a mis compañeros

2022-07-28 20:41 UTC, anagon88 commented on src/app/features/pages/backoffice/users-list/users-list.component.ts
> +    // this.getUsers()
igual, no subir codigo comentado, hacerle un undo de esos archivos

2022-07-28 22:09 UTC, gastoncorrea commented on src/app/features/pages/backoffice/users-list/users-list.component.ts
> +    // this.getUsers()
ok, comentarios borrados.

2022-07-29 15:48 UTC, anagon88 approved these changes

2022-07-29 15:48 UTC, merged