Features/ot257 57
alkemyTech/OT257-Client pull request #41
Opened 2022-07-27 15:02 UTC by gastoncorrea

![actividades](https://user-images.githubusercontent.com/74715944/181281152-a26186b1-1fc8-4cab-8ccd-55f632be955d.png)

2022-07-28 16:18 UTC, anagon88 requested changes

2022-07-28 16:18 UTC, anagon88 commented on src/app/core/services/activity/activities.service.ts
> +  // getListActivity(): Observable<any>{
esta bien el codigo comentado?

2022-07-28 16:18 UTC, anagon88 commented on src/app/features/pages/backoffice/users-list/users-list.component.ts
> +  // getUsers() {
esta bien codigo comentado?

2022-07-28 22:21 UTC, gastoncorrea commented on src/app/features/pages/backoffice/users-list/users-list.component.ts
> +  // getUsers() {
comentarios borrados

2022-07-29 15:49 UTC, anagon88 requested changes

2022-07-29 15:49 UTC, anagon88 commented on src/app/core/services/activity/activities.service.ts
> +  // getListActivity(): Observable<any>{
falto este

2022-07-29 18:11 UTC, merged