Features/ot257 110
alkemyTech/OT257-Client pull request #55
Opened 2022-08-02 02:38 UTC by gastoncorrea

![slide-list template](https://user-images.githubusercontent.com/74715944/182278176-e312da8a-e19b-4cc0-baef-a0df26f0e09b.png)
![slider-list component ts](https://user-images.githubusercontent.com/74715944/182278193-9da1ff53-4182-4874-b4d9-ab48ff25135a.png)
![slider action ts](https://user-images.githubusercontent.com/74715944/182278207-13023edb-68c6-42dd-a9f1-544388369508.png)
![slide effect ts](https://user-images.githubusercontent.com/74715944/182278217-25cf54b2-5a51-4820-9b64-7cce75133210.png)
![slider reducer  ts](https://user-images.githubusercontent.com/74715944/182278237-21afb3be-d5ff-42b3-88c5-c49ad4b4486b.png)
![App state  ts](https://user-images.githubusercontent.com/74715944/182278286-9d922c55-c645-439c-9390-971ba9d4b4fa.png)
![slider selector ts](https://user-images.githubusercontent.com/74715944/182278318-649e66f4-1d0b-42c2-ac83-f5a91847a53e.png)
![effect init](https://user-images.githubusercontent.com/74715944/182279515-c8f4c124-5f52-4674-a630-93a527a40492.png)
![load slide efect](https://user-images.githubusercontent.com/74715944/182279697-62bbb961-c63a-423c-9d2c-535928b4c1cc.png)
![get slide action](https://user-images.githubusercontent.com/74715944/182279842-b150a9a2-f529-42a0-8036-e1a7ee545a8d.png)

2022-08-02 17:21 UTC, anagon88 requested changes

2022-08-02 17:21 UTC, anagon88 commented on src/app/features/pages/slides/list-slides/list-slides/list-slides.component.ts
> +    private slideService: SlideFormService,
no se deberia usar mas el servicio aca

2022-08-02 17:21 UTC, anagon88 commented on src/app/features/pages/slides/list-slides/list-slides/list-slides.component.ts
> +        // this.store.dispatch(deleteSlider({ id }))
deberia llamar al store no al servicio

2022-08-02 17:21 UTC, anagon88 commented on src/app/state/effects/slider.effects.ts
> +
faltan effects de eliminar, crear y editar

2022-08-05 21:40 UTC, gastoncorrea commented on src/app/state/effects/slider.effects.ts
> +
crud completo con ngrx

2022-08-06 22:49 UTC, anagon88 approved these changes

2022-08-06 22:49 UTC, anagon88 commented on src/app/features/backoffice/pages/slides/slides-form/slides-form.component.ts
> +          console.log(slide);
elimina consolo log

2022-08-07 17:26 UTC, merged