Features/ot257 107
alkemyTech/OT257-Client pull request #63
Opened 2022-08-04 21:28 UTC by wilago

Se termina el crud de Ngrx.

![image](https://user-images.githubusercontent.com/27816405/182955908-1ba75aae-eefd-478a-934d-ca01071fae16.png)

2022-08-06 22:57 UTC, anagon88 requested changes

2022-08-06 22:57 UTC, anagon88 commented on src/app/features/pages/backoffice/news/news-form/news-form.component.ts
> +    this.newsService
borrar comentado

2022-08-06 22:57 UTC, anagon88 commented on src/app/features/pages/backoffice/news/news-form/news-form.component.ts
> +      console.log('this.form.value',this.form.value);
borrar console log

2022-08-06 22:57 UTC, anagon88 commented on src/app/features/pages/backoffice/news/news-form/news-form.component.ts
> +      //this.router.navigate([`/backoffice/news/`]);
borrar comentado

2022-08-06 22:57 UTC, anagon88 commented on src/app/features/pages/backoffice/news/news/news.component.ts
> +    this.newService.getNews().pipe(
borrar este service

2022-08-06 22:57 UTC, anagon88 commented on src/app/features/pages/backoffice/news/news/news.component.ts
> +          this.newService.deleteNew(id).subscribe((resp) => {
borrar comentado

2022-08-07 01:41 UTC, wilago commented on src/app/features/pages/backoffice/news/news-form/news-form.component.ts
> +    this.newsService
Eliminado

2022-08-07 01:41 UTC, wilago commented on src/app/features/pages/backoffice/news/news-form/news-form.component.ts
> +      console.log('this.form.value',this.form.value);
Eliminado

2022-08-07 01:42 UTC, wilago commented on src/app/features/pages/backoffice/news/news/news.component.ts
> +          this.newService.deleteNew(id).subscribe((resp) => {
Eliminado

2022-08-09 19:12 UTC, merged