Feature/ot257 127
alkemyTech/OT257-Client pull request #65
Opened 2022-08-06 00:31 UTC by ValentinaRippe

![footer](https://user-images.githubusercontent.com/94970159/183226309-e79dcbf8-cb6a-46f0-835e-23e6f7f838b4.png)

2022-08-06 23:05 UTC, anagon88 requested changes

2022-08-06 23:05 UTC, anagon88 commented on src/app/shared/components/footer/footer.component.ts
> +      console.log(res);
borrar console log

2022-08-06 23:05 UTC, anagon88 commented on src/app/state/reducers/auth.reducer.ts
> +  logInGoogle,
codigo agregado en otro pr

2022-08-07 16:00 UTC, ValentinaRippe commented on src/app/state/reducers/auth.reducer.ts
> +  logInGoogle,
Saque sin darme cuenta la rama 127 de la rama del login con google que es la 122, ya igualmente subi ese pr del login con google al main, entonces al hacer el merge no creo que hayan conflictos, no sabria como más solucionarlo.

2022-08-08 12:29 UTC, anagon88 approved these changes

2022-08-10 15:38 UTC, merged