Features/ot257 137
alkemyTech/OT257-Client pull request #74
Opened 2022-08-11 05:11 UTC by wilago

Creación del landing de Juguetes

![image](https://user-images.githubusercontent.com/27816405/184068120-5de09d63-96ff-488f-a851-9d5e5a424d98.png)

Se realiza la parte responsiva para movil
![image](https://user-images.githubusercontent.com/27816405/184068318-c6cfd6b6-b2a3-494b-a6e7-fff551206684.png)

2022-08-11 21:57 UTC, anagon88 requested changes

2022-08-11 21:57 UTC, anagon88 commented on src/app/features/public/pages/langings/juguetes/juguetes.component.html
> +<div class="movillogo px-5 mt-5">
formatear documento

2022-08-11 21:57 UTC, anagon88 commented on src/app/features/public/pages/langings/juguetes/juguetes.component.ts
> +    //console.log(this.tiempoFaltante)
eliminar linea comentada

2022-08-11 21:57 UTC, anagon88 commented on src/app/features/public/pages/langings/juguetes/juguetes.component.ts
> +import { ClassGetter } from '@angular/compiler/src/output/output_ast';
el nombre juguetes.component tiene que ser en ingles

2022-08-11 21:57 UTC, anagon88 commented on src/app/features/public/public.module.ts
> +    JuguetesComponent,
cambiar el nombre a ToysComponent

2022-08-11 21:57 UTC, anagon88 commented on src/app/shared/components/backoffice/sidebar/sidebar.component.html
> +<div class="app" style="display: flex; height: 100%; overflow: scroll initial">
poner el style en el archivo scss

2022-08-11 21:57 UTC, anagon88 commented on src/app/shared/components/backoffice/sidebar/sidebar.component.html
> +        <div class="sidebar-btn-wrapper" style="padding: 20px 5px">
pasar el style al archivos scss

2022-08-11 21:57 UTC, anagon88 commented on src/app/shared/components/backoffice/sidebar/sidebar.component.ts
> +import { Component, OnInit } from '@angular/core';
este componente corresponde a otra user story?

2022-08-12 21:24 UTC, wilago commented on src/app/shared/components/backoffice/sidebar/sidebar.component.ts
> +import { Component, OnInit } from '@angular/core';
Pienso que si, a no ser que lo hay mal interpretado.

2022-08-16 19:39 UTC, anagon88 approved these changes

2022-08-18 00:13 UTC, merged